Update prod_gymsync.yml

diff --git a/.github/workflows/prod_gymsync.yml b/.github/workflows/prod_gymsync.yml
--- a/.github/workflows/prod_gymsync.yml
+++ b/.github/workflows/prod_gymsync.yml
@@ -26,10 +26,10 @@ jobs:
       - name: Install dependencies
         run: pip install -r requirements.txt
 
-      - name: Cleaning testing files
+      - name: Clean up testing files (if they exist)
         run: |
-          rm db.sqlite3
-          rm .env
+          [ -f db.sqlite3 ] && rm db.sqlite3 || echo "db.sqlite3 not found, skipping"
+          [ -f .env ] && rm .env || echo ".env not found, skipping"
           cd ..
 
       - name: Zip artifact for deployment
